# Site wide configuration

environment: production
title: Milk Mustache
locale: en_US
description: The Joy of Eating
logo: site-logo.svg
search: true
url: http://milk-mustache.com
uploads_path: uploads
encoding: UTF-8
source: src

# Jekyll configuration

# Build settings
environment: production
permalink:   /:categories/:title/
markdown: kramdown
sass:
  sass_dir: _styles

exclude: ["*.spec.js", "lib", "log", "tmp", "test", "spec", "vendor"]
autoprefixer:
  browsers:
    - last 2 versions
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll/responsive_image
  - jekyll-paginate
  - jekyll-babel
  - jekyll-autoprefixer
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true


# Pagination

paginate: 10


# Site owner
owner:
  name: Sarah Quigley
  avatar: about.jpg
  email: sarah+milk-mustache@sarahquigley.net
  formspree-email: sarah@sarahquigley.net
  disqus-shortname: milkmustache
  twitter: thejoyofeating
  facebook: thejoyofeating
  github: sarahquigley
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: ohmilkmustache
  flickr: #username
  tumblr: #username
  pinterest: ohmilkmustache
  weibo: #userid
  soundcloud: sarah-quigley-542895767
  medium: milk-mustache
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  template: src/_includes/image.html
  default_quality: 90
  sizes:
    - width: 480
    - width: 620
    - width: 768
    - width: 1000
    - width: 1400
    - width: 2000
  base_path: src/uploads
  output_path_format: src/uploads/resized/%{dirname}/%{width}/%{basename}
